In [1]:

#   base_path: "data/ArchiveII_max_length_128.csv"
#   partition_path: "data/famfold/ArchiveII_famfold.csv"

In [2]:
import pandas as pd
from pathlib import Path

base_path = Path("../data/ArchiveII_max_length_128.csv")
partition_path = Path("../data/famfold/ArchiveII_famfold.csv")

df = pd.read_csv(base_path, index_col="id")
partition_df = pd.read_csv(partition_path, index_col="id")
print("Base DataFrame:")
display(df.head(2))
print("\nPartition DataFrame:")
display(partition_df.head(2))

Base DataFrame:

,sequence,structure,base_pairs,len,fam
id,,,,,
5s_Acholeplasma-laidlawii-1,UCUGGUGACGAUAGGUAAGAUGGUUCACCUGUUCCCAUCCCGAACA...,((((((((......((((((((....((((((.............)...,"[[1, 111], [2, 110], [3, 109], [4, 108], [5, 1...",112,5s
5s_Acidovorax-temperans-1,UGCCUGAUGACCAUAGCAAGUUGGUACCACUCCUUCCCAUCCCGAA...,.(((((((((.....((((((((.....((((((...............,"[[2, 115], [3, 114], [4, 113], [5, 112], [6, 1...",115,5s

Partition DataFrame:

                       fold partition
id
16s_A.fulgidus_domain2  16s      test
16s_A.fulgidus_domain3  16s      test

In [8]:
df.query(" len < 128").fam.value_counts()

fam
5s      1266
tRNA     557
srp      493
Name: count, dtype: int64

In [3]:
train_ids = partition_df.loc[(partition_df["fold"] == "23s") & (partition_df["partition"] == "train")].index
common = list(set(train_ids).intersection(df.index))
df_train = df.loc[common]
print("\nTrain DataFrame:")
display(df_train.head(2))
df_train.shape

Train DataFrame:

,sequence,structure,base_pairs,len,fam
id,,,,,
5s_Limulus-polyphemus-1,GUCAUCGUUCAUACCACGUUGAAAGCGCCGGUUCUCGUCUGAUCCC...,(((((((((....((((((((.....(((((..............)...,"[[1, 118], [2, 117], [3, 116], [4, 115], [5, 1...",120,5s
5s_Vitreoscilla-beggiatoides-1,CGCCUGACGACCACAGCGACUGUGAACCACCCGACCCCAUCUCGAA...,.(((((((((.....(((((((......((((((...............,"[[2, 117], [3, 116], [4, 115], [5, 114], [6, 1...",118,5s

(2075, 5)

In [4]:
train_ids = partition_df.loc[(partition_df["fold"] == "23s") & (partition_df["partition"] == "test")].index
common = list(set(train_ids).intersection(df.index))
df_train = df.loc[common]
print("\nTrain DataFrame:")
display(df_train.head(2))
df_train.shape

Train DataFrame:

Empty DataFrame
Columns: [sequence, structure, base_pairs, len, fam]
Index: []

(0, 5)